# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a9bd93933ba769632eb43d3791ef98c8d7f0c861444626ae914a03f10d5ec5117f5f3a0369d5367c8dfac1860df59d3e90899c02ab43597abdff8ba5abfeae7

test:
  secret_key_base: 1d33c7d0ab768f4e3787fcfa3716a8c6822790a091587dc4621590e6cc977fb219e07fd4dc7c1a1c98773cd74cbbf728228f70e2e57f262ccc14a295d1f18c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
